# Generated by Django 3.1.6 on 2021-02-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tests', '0002_auto_20210204_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
